name: Create Self-Service Action in Port

on:
  workflow_dispatch:
    inputs:
      port_context:
        description: 'Complete context from Port as JSON string'
        required: true

jobs:
  create_ssa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Debug Environment
        run: |
          which python
          python --version

      - name: Create Self-Service Action
        run: |
          import json
          import requests
          import os

          # Fetch the port context from GitHub Actions input
          port_context_json = '${{ github.event.inputs.port_context }}'
          port_context = json.loads(port_context_json)

          # Construct the SSA JSON using the port context
          ssa_data = {
              "identifier": port_context['identifier'],  # Update as per your actual JSON structure
              "title": port_context['title'],
              "description": port_context.get('description', 'No description provided'),
              "trigger": {
                  "type": "self-service",
                  "operation": port_context['operation'],
                  "userInputs": port_context
              },
              "invocationMethod": {
                  "type": port_context.get('invocation_type', 'RUN_GITHUB_ACTION'),
                  "endpointUrl": port_context.get('webhook_endpoint_url', '')
              }
          }

          # Post request to Port's API
          response = requests.post(
              'https://api.getport.io/v1/actions',
              json=ssa_data,
              headers={'Authorization': 'Bearer ' + os.getenv('YOUR_PORT_API_TOKEN')}
          )

          # Check response
          if response.status_code == 200:
              print('SSA created successfully')
          else:
              print('Failed to create SSA:', response.text)
        env:
          YOUR_PORT_API_TOKEN: ${{ secrets.PORT_API_TOKEN }}
